name: Draft release
run-name: Draft release ${{ inputs.next_version }}

on:
  workflow_dispatch:
    inputs:
      next_version:
        required: true
        type: string
        description: 'Version name'

permissions:
  contents: write

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: develop branch change
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout develop

      - name: Modify README.md
        uses: jaywcjlove/github-action-modify-file-content@main
        with:
          path: README.md
          body: "Version ${{ inputs.next_version }}"

      - name: update version name
        uses: jaywcjlove/github-action-package@main
        with:
          path: 'package.json'
          version: ${{ inputs.next_version }}

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update version to ${{ inputs.next_version }}"
          git push

      - name: Merge develop
        run: |
          git checkout develop
          git pull
          git checkout main
          git merge origin/develop
          git push

      - name: Draft release
        run: gh release create $VERSION --generate-notes --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ inputs.next_version }}
